## Preprocessing

In [35]:
# Importing the libraries
%config IPCompleter.greedy=True
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
pd.options.display.float_format = '{:,.2f}'.format
np.set_printoptions(suppress=True)
# Importing the dataset
dataset = pd.read_csv('50_Startups.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 4].values

from sklearn.preprocessing import Imputer
imputer = Imputer(missing_values = 'NaN', strategy = 'mean', axis = 0)
imputer = imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

# Encoding categorical data
# Encoding the Independent Variable
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X = LabelEncoder()
X[:, 3] = labelencoder_X.fit_transform(X[:, 3])
onehotencoder = OneHotEncoder(categorical_features = [3])
X = onehotencoder.fit_transform(X).toarray()

#Dummy Varibale Trap
X = X[:, 1:]

# Splitting the dataset into the Training set and Test set
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Feature Scaling
"""from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)
sc_y = StandardScaler()
y_train = sc_y.fit_transform(y_train)"""

'from sklearn.preprocessing import StandardScaler\nsc_X = StandardScaler()\nX_train = sc_X.fit_transform(X_train)\nX_test = sc_X.transform(X_test)\nsc_y = StandardScaler()\ny_train = sc_y.fit_transform(y_train)'

# Dummy Variable Trap

In [36]:
dataset

R&D Spend  Administration  Marketing Spend       State     Profit
0  165,349.20      136,897.80       471,784.10    New York 192,261.83
1  162,597.70      151,377.59       443,898.53  California 191,792.06
2  153,441.51      101,145.55       407,934.54     Florida 191,050.39
3  144,372.41      118,671.85       383,199.62    New York 182,901.99
4  142,107.34       91,391.77       366,168.42     Florida 166,187.94
5  131,876.90       99,814.71       362,861.36    New York 156,991.12
6  134,615.46      147,198.87       127,716.82  California 156,122.51
7  130,298.13      145,530.06       323,876.68     Florida 155,752.60
8  120,542.52      148,718.95       311,613.29    New York 152,211.77
9  123,334.88      108,679.17       304,981.62  California 149,759.96
10 101,913.08      110,594.11       229,160.95     Florida 146,121.95
11 100,671.96       91,790.61       249,744.55  California 144,259.40
12  93,863.75      127,320.38       249,839.44     Florida 141,585.52
13  91,992.39      135,495.07       252,664.93  California 134,307.35
14 119,943.24      156,547.42       256,512.92     Florida 132,602.65
15 114,523.61      122,616.84       261,776.23    New York 129,917.04
16  78,013.11      121,597.55       264,346.06  California 126,992.93
17  94,657.16      145,077.58       282,574.31    New York 125,370.37
18  91,749.16      114,175.79       294,919.57     Florida 124,266.90
19  86,419.70      153,514.11             0.00    New York 122,776.86
20  76,253.86      113,867.30       298,664.47  California 118,474.03
21  78,389.47      153,773.43       299,737.29    New York 111,313.02
22  73,994.56      122,782.75       303,319.26     Florida 110,352.25
23  67,532.53      105,751.03       304,768.73     Florida 108,733.99
24  77,044.01       99,281.34       140,574.81    New York 108,552.04
25  64,664.71      139,553.16       137,962.62  California 107,404.34
26  75,328.87      144,135.98       134,050.07     Florida 105,733.54
27  72,107.60      127,864.55       353,183.81    New York 105,008.31
28  66,051.52      182,645.56       118,148.20     Florida 103,282.38
29  65,605.48      153,032.06       107,138.38    New York 101,004.64
30  61,994.48      115,641.28        91,131.24     Florida  99,937.59
31  61,136.38      152,701.92        88,218.23    New York  97,483.56
32  63,408.86      129,219.61        46,085.25  California  97,427.84
33  55,493.95      103,057.49       214,634.81     Florida  96,778.92
34  46,426.07      157,693.92       210,797.67  California  96,712.80
35  46,014.02       85,047.44       205,517.64    New York  96,479.51
36  28,663.76      127,056.21       201,126.82     Florida  90,708.19
37  44,069.95       51,283.14       197,029.42  California  89,949.14
38  20,229.59       65,947.93       185,265.10    New York  81,229.06
39  38,558.51       82,982.09       174,999.30  California  81,005.76
40  28,754.33      118,546.05       172,795.67  California  78,239.91
41  27,892.92       84,710.77       164,470.71     Florida  77,798.83
42  23,640.93       96,189.63       148,001.11  California  71,498.49
43  15,505.73      127,382.30        35,534.17    New York  69,758.98
44  22,177.74      154,806.14        28,334.72  California  65,200.33
45   1,000.23      124,153.04         1,903.93    New York  64,926.08
46   1,315.46      115,816.21       297,114.46     Florida  49,490.75
47       0.00      135,426.92             0.00  California  42,559.73
48     542.05       51,743.15             0.00    New York  35,673.41
49       0.00      116,983.80        45,173.06  California  14,681.40

In [37]:
X,y

(array([[      0.  ,       1.  ,  165349.2 ,  136897.8 ,  471784.1 ],
        [      0.  ,       0.  ,  162597.7 ,  151377.59,  443898.53],
        [      1.  ,       0.  ,  153441.51,  101145.55,  407934.54],
        [      0.  ,       1.  ,  144372.41,  118671.85,  383199.62],
        [      1.  ,       0.  ,  142107.34,   91391.77,  366168.42],
        [      0.  ,       1.  ,  131876.9 ,   99814.71,  362861.36],
        [      0.  ,       0.  ,  134615.46,  147198.87,  127716.82],
        [      1.  ,       0.  ,  130298.13,  145530.06,  323876.68],
        [      0.  ,       1.  ,  120542.52,  148718.95,  311613.29],
        [      0.  ,       0.  ,  123334.88,  108679.17,  304981.62],
        [      1.  ,       0.  ,  101913.08,  110594.11,  229160.95],
        [      0.  ,       0.  ,  100671.96,   91790.61,  249744.55],
        [      1.  ,       0.  ,   93863.75,  127320.38,  249839.44],
        [      0.  ,       0.  ,   91992.39,  135495.07,  252664.93],
        [      1.  ,

## Doing the fun part

In [38]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

## Predicting the test result

## Markdown test

In [39]:
y_pred = regressor.predict(X_test)

In [40]:
y_pred,y_test

(array([ 103015.20159795,  132582.27760817,  132447.73845176,
          71976.09851257,  178537.48221058,  116161.24230165,
          67851.69209675,   98791.73374686,  113969.43533013,
         167921.06569553]),
 array([ 103282.38,  144259.4 ,  146121.95,   77798.83,  191050.39,
         105008.31,   81229.06,   97483.56,  110352.25,  166187.94]))

## Backward Elimination

In [41]:
import statsmodels.formula.api as sm 
## sm doesnot take into account b0 in y = b0 + b1 * x1 so we need to add column of 1's to make x0 as 1
X = np.append(arr = np.ones((50,1)).astype(int), values = X, axis=1)

In [42]:
X

array([[      1.  ,       0.  ,       1.  ,  165349.2 ,  136897.8 ,
         471784.1 ],
       [      1.  ,       0.  ,       0.  ,  162597.7 ,  151377.59,
         443898.53],
       [      1.  ,       1.  ,       0.  ,  153441.51,  101145.55,
         407934.54],
       [      1.  ,       0.  ,       1.  ,  144372.41,  118671.85,
         383199.62],
       [      1.  ,       1.  ,       0.  ,  142107.34,   91391.77,
         366168.42],
       [      1.  ,       0.  ,       1.  ,  131876.9 ,   99814.71,
         362861.36],
       [      1.  ,       0.  ,       0.  ,  134615.46,  147198.87,
         127716.82],
       [      1.  ,       1.  ,       0.  ,  130298.13,  145530.06,
         323876.68],
       [      1.  ,       0.  ,       1.  ,  120542.52,  148718.95,
         311613.29],
       [      1.  ,       0.  ,       0.  ,  123334.88,  108679.17,
         304981.62],
       [      1.  ,       1.  ,       0.  ,  101913.08,  110594.11,
         229160.95],
       [      1.  ,  

In [43]:
X_opt = X[:, [0,1,2,3,4,5]] 
regressor_OLS = sm.OLS(endog = y, exog = X_opt).fit() 
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.945
Method:                 Least Squares   F-statistic:                     169.9
Date:                Sun, 07 Jan 2018   Prob (F-statistic):           1.34e-27
Time:                        14:44:58   Log-Likelihood:                -525.38
No. Observations:                  50   AIC:                             1063.
Df Residuals:                      44   BIC:                             1074.
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [95.0% Conf. Int.]
------------------------------------------------------------------------------
const       5.013e+04   6884.820      7.281      0.000      3.62e+04   6.4e+04
x1           198.7888   3371.007      0.059      0.953     -6595.030  6992.607
x2           -41.8870   3256.039     -0.013      0.990     -6604.003  6520.229
x3             0.8060      0.046     17.369      0.000         0.712     0.900
x4            -0.0270      0.052     -0.517      0.608        -0.132     0.078
x5             0.0270      0.017      1.574      0.123        -0.008     0.062
==============================================================================
Omnibus:                       14.782   Durbin-Watson:                   1.283
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.266
Skew:                          -0.948   Prob(JB):                     2.41e-05
Kurtosis:                       5.572   Cond. No.                     1.45e+06
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.45e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [44]:
X_opt = X[:, [0,1,3,4,5]] 
regressor_OLS = sm.OLS(endog = y, exog = X_opt).fit() 
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.946
Method:                 Least Squares   F-statistic:                     217.2
Date:                Sun, 07 Jan 2018   Prob (F-statistic):           8.49e-29
Time:                        14:44:58   Log-Likelihood:                -525.38
No. Observations:                  50   AIC:                             1061.
Df Residuals:                      45   BIC:                             1070.
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [95.0% Conf. Int.]
------------------------------------------------------------------------------
const       5.011e+04   6647.870      7.537      0.000      3.67e+04  6.35e+04
x1           220.1585   2900.536      0.076      0.940     -5621.821  6062.138
x2             0.8060      0.046     17.606      0.000         0.714     0.898
x3            -0.0270      0.052     -0.523      0.604        -0.131     0.077
x4             0.0270      0.017      1.592      0.118        -0.007     0.061
==============================================================================
Omnibus:                       14.758   Durbin-Watson:                   1.282
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.172
Skew:                          -0.948   Prob(JB):                     2.53e-05
Kurtosis:                       5.563   Cond. No.                     1.40e+06
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.4e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [45]:
X_opt = X[:, [0,3,4,5]] 
regressor_OLS = sm.OLS(endog = y, exog = X_opt).fit() 
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.948
Method:                 Least Squares   F-statistic:                     296.0
Date:                Sun, 07 Jan 2018   Prob (F-statistic):           4.53e-30
Time:                        14:46:24   Log-Likelihood:                -525.39
No. Observations:                  50   AIC:                             1059.
Df Residuals:                      46   BIC:                             1066.
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [95.0% Conf. Int.]
------------------------------------------------------------------------------
const       5.012e+04   6572.353      7.626      0.000      3.69e+04  6.34e+04
x1             0.8057      0.045     17.846      0.000         0.715     0.897
x2            -0.0268      0.051     -0.526      0.602        -0.130     0.076
x3             0.0272      0.016      1.655      0.105        -0.006     0.060
==============================================================================
Omnibus:                       14.838   Durbin-Watson:                   1.282
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.442
Skew:                          -0.949   Prob(JB):                     2.21e-05
Kurtosis:                       5.586   Cond. No.                     1.40e+06
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.4e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [46]:
X_opt = X[:, [0,3,5]] 
regressor_OLS = sm.OLS(endog = y, exog = X_opt).fit() 
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.950
Model:                            OLS   Adj. R-squared:                  0.948
Method:                 Least Squares   F-statistic:                     450.8
Date:                Sun, 07 Jan 2018   Prob (F-statistic):           2.16e-31
Time:                        14:46:52   Log-Likelihood:                -525.54
No. Observations:                  50   AIC:                             1057.
Df Residuals:                      47   BIC:                             1063.
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [95.0% Conf. Int.]
------------------------------------------------------------------------------
const       4.698e+04   2689.933     17.464      0.000      4.16e+04  5.24e+04
x1             0.7966      0.041     19.266      0.000         0.713     0.880
x2             0.0299      0.016      1.927      0.060        -0.001     0.061
==============================================================================
Omnibus:                       14.677   Durbin-Watson:                   1.257
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.161
Skew:                          -0.939   Prob(JB):                     2.54e-05
Kurtosis:                       5.575   Cond. No.                     5.32e+05
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.32e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [47]:
X_opt = X[:, [0,3]] 
regressor_OLS = sm.OLS(endog = y, exog = X_opt).fit() 
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.947
Model:                            OLS   Adj. R-squared:                  0.945
Method:                 Least Squares   F-statistic:                     849.8
Date:                Sun, 07 Jan 2018   Prob (F-statistic):           3.50e-32
Time:                        14:53:24   Log-Likelihood:                -527.44
No. Observations:                  50   AIC:                             1059.
Df Residuals:                      48   BIC:                             1063.
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [95.0% Conf. Int.]
------------------------------------------------------------------------------
const       4.903e+04   2537.897     19.320      0.000      4.39e+04  5.41e+04
x1             0.8543      0.029     29.151      0.000         0.795     0.913
==============================================================================
Omnibus:                       13.727   Durbin-Watson:                   1.116
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               18.536
Skew:                          -0.911   Prob(JB):                     9.44e-05
Kurtosis:                       5.361   Cond. No.                     1.65e+05
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.65e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [50]:
X.size()

TypeError: 'int' object is not callable